#https://github.com/terrakok/kmp-awesome

[versions]
gene-conventions = "2.1.17"
plugin-publish = "1.3.0"

[libraries]
plugin-publish = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "plugin-publish" }

[plugins]